prior:
  draws: 200
  random_seed: 11

initialization:
  rl_init: true

nuts:
  nuts_sampler: pymc
  draws: 200
  tune: 200
  chains: 2
  target_accept: 0.95
  max_treedepth: 10
  random_seed: 12

  pymc:
    cores: 2
    init: jitter+adapt_diag
    dense_mass: false
    progressbar: true
